language: python
python: 3.5

env:
  - TOXENV=py35
  - TOXENV=flake8

before_install:
  - source /etc/lsb-release
  - sudo apt-get update -qq

install:
  - pip install -U codecov tox

script: tox -e ${TOXENV}

after_success: codecov
