language: python
python: 3.5

before_cache:
  - rm -rf $HOME/.cache/pip/log
cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install -e .[test]
  - pip install codecov

script: py.test -v --cov

after_success: codecov
